function [EEGOUT COMMANDS] = pop_grand_average(EEG, inargs)

% the command output is a hidden output that does not have to
% be described in the header

COMMANDS = ''; % this initialization ensure that the function will return something
% if the user press the cancel button
EEGOUT = EEG;
% display help if not enough arguments
% ------------------------------------
if nargin < 1
    help pop_rozruch;
    return;
end;


if(nargin == 2)
    switch inargs
        case {'current_dataset','all_datasets'},
            % Push buttons that call for action
            gui_params = struct();
            gui_params.data_display = get(findobj('tag','data_display'), 'value');
            gui_params.figure_name = get(findobj('tag','figure_name'),'string');
            gui_params.invert_polarity = get(findobj('tag','invert_polarity'), 'value');
            gui_params.event_based_constraints = get(findobj('tag','event_based_constraints'), 'string');
            gui_params.include_non_smoothed_data = get(findobj('tag','include_non_smoothed_data'), 'value');
            gui_params.data_zero = get(findobj('tag','data_zero'), 'value');
            gui_params.data_save = get(findobj('tag','data_save'), 'value');
            gui_params.data_name = get(findobj('tag','data_name'), 'string');
            gui_params.smoothing = str2double(get(findobj('tag','smoothing'), 'string'));
            gui_params.type = inargs;
            averaging(EEG,gui_params);
        otherwise,
            error('Input parameter unrecognised, consult help or use GUI');
    end;
    
else
    % Definition of window geometry
    geom = { ...
        1 ...                                   % Warning
        1 ...
        [0.2 0.6 0.2]...                        % Grand average
        1 ...
        [0.2 0.6 0.2]...                        % Epoch based
        1 ...                                   % Settings
        1 ...                                   % | 'What to do...'
        [0.15 0.1 0.75] ...                     % | Smoothing
        1 ...            
        [0.2 0.15 0.25 ] ...                    % | Display
        1 ...            
        [0.2 0.15 0.25 ] ...                    % | 
        [0.15 0.15 0.15 ] ...                   % |
        };
    
    
    % Definition of window elements
    uilist = { ... Current dataset
        { 'style', 'text', 'string', 'Warning: do not open multiple instances of this window, it may cause failure of the program.' 'fontweight' 'bold'}, ...
        ...
        { }...     
        ...
        { 'style', 'text', 'string', 'Current dataset' 'fontweight' 'bold'}, ...
        { 'style', 'text', 'string', '(calculates one average signal from all epochs and channels)' }, ...
        { 'style', 'pushbutton' , 'string', 'Calculate', 'callback', 'pop_grand_average(EEG,''current_dataset'');' }...
        ...
        { }...        
        ... All datasets
        { 'style', 'text', 'string', 'All datasets' 'fontweight' 'bold'}, ...
        { 'style', 'text', 'string', '(calculates average from all datasets)' }, ...
        { 'style', 'pushbutton' , 'string', 'Calculate','callback', 'pop_grand_average(EEG,''all_datasets'');' }...
        ...
        { },...       
        ... Settings
        { 'style', 'text', 'string', 'Settings' 'fontweight' 'bold' }, ...
        ...
        { 'style', 'text', 'string', 'Smoothing' }, ...
        { 'style', 'edit', 'string', '1', 'tag', 'smoothing' }, ...
        { 'style', 'text', 'string', '(width of smoothing window in datapoints; 1 = no smoothing)' }, ...
        ...
        { },...       
        ...
        { 'style', 'checkbox', 'string', 'Save as new dataset', 'tag', 'data_save', 'value', 0}, ...
        { 'style', 'text', 'string', 'Dataset name'}, ...
        { 'style', 'edit', 'string', [EEG.setname ' - Grand Average'], 'tag', 'data_name' }, ...
        ...
        { },...     
        ...
        { 'style', 'checkbox', 'string', 'Display', 'tag', 'data_display', 'value', 1}, ...
        { 'style', 'text', 'string', 'Figure name'}, ...
        { 'style', 'edit', 'string', EEG.setname, 'tag', 'figure_name' }, ...
        ...
        { 'style', 'checkbox', 'string', 'Invert polarity (''ERP View'')', 'tag', 'invert_polarity', 'value', 1}, ...
        { 'style', 'checkbox', 'string', 'Include non-smoothed data', 'tag', 'include_non_smoothed_data', 'value', 1}, ...
        { 'style', 'checkbox', 'string', 'Display zero-axes', 'tag', 'data_zero', 'value', 1}, ...
        };
    
    % And here we go with the window
    supergui( 'title', 'Grand Average','geomhoriz', geom, 'uilist',  uilist);
end
return;



